### ISSUE TITLE
Add Whitelisted Jobs to Job Center

### ISSUE THREAD

**Issue by HumanTree92** [esx-framework/esx_joblisting#24]
This isn't much of an issue it would just be nice to have it all in one script. Not sure why it wouldn't be included. But add something like [esx_JobWhitelisting](https://forum.cfx.re/t/release-esx-esx-jobwhitelisting-whitelist-jobs-and-ranks-to-certain-players/224548)

**Comment by christerjohansson** [comment]
Yes, I agree. I would very much like to be able to whitelist certain jobs, and they would only show to those who are whitelisted on server. I am not good with Lua, so I can't do it myself. But it would probably be something like check a players name in DB, if they are whitelisted (1 or 0) and then show available jobs based on that. 

Why?
Because I don't want to whitelist my entire server, but only certain things. This allows for new players to come in and play, and if they want to stay and do whitelisted jobs...they can apply for whitelisting. Rather than closing down the entire server behind a whitelisting feature.

**Comment by HumanTree92** [comment]
I have done this already. Check it out https://github.com/HumanTree92/esx_joblisting
